#!/usr/bin/env python3
"""Build HYDRADB-CAPABILITIES.md from the probe reports themselves.

    python3 tools/capabilities.py > HYDRADB-CAPABILITIES.md

Every line in the output is derived from a JSON verdict written by a probe run
against a live HydraDB 0.1.0 node. Nothing is typed from memory, which is the
point: a capability map that a reader has to take on trust is worth less than
one they can regenerate.

It also reconciles the probes against each other, and that reconciliation is
the most useful thing in the file. The first probe reported almost the whole
surface as unsupported. Probes 2-6 then found the working syntax and overturned
eight of those verdicts. Those eight are printed as an explicit correction
table rather than quietly dropped, because the lesson generalises:

  AN "UNSUPPORTED" VERDICT FROM A PROBE IS A STATEMENT ABOUT THE PROBE UNTIL
  THE ALTERNATIVE SHAPES HAVE BEEN TRIED.

probe1 wrote `CREATE (n:Label {props})` with no integer id and concluded that
labelled CREATE was unsupported. The engine wanted a one-hop edge pattern with
an integer id on both ends. The engine was fine; the query was wrong.
"""
from __future__ import annotations

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

# (path, human label). probe1 lives at the repo root and uses an older shape.
SOURCES = [
    (os.path.join(ROOT, "probe-report.json"), "probe1"),
    (os.path.join(HERE, "probe2-report.json"), "probe2"),
    (os.path.join(HERE, "probe3-report.json"), "probe3"),
    (os.path.join(HERE, "probe4-report.json"), "probe4"),
    (os.path.join(HERE, "probe5-report.json"), "probe5"),
    (os.path.join(HERE, "probe6-report.json"), "probe6"),
]

# probe1 name -> the later check that overturned it. Each pair is asserted
# against the loaded data below, so a wrong mapping fails loudly rather than
# printing a correction that did not happen.
OVERTURNED = [
    ("parameters_parameters_key", "key_parameters"),
    ("where_comparison", "labelled_interval"),
    ("variable_length_path", "var_len_1_3"),
    ("optional_match", "optional_match"),
    ("unicode_and_quotes", "unicode_and_quote"),
    ("long_string_property", "long_string_as_parameter"),
    ("delete", "delete_edge"),
    ("create_with_label_and_props", "label_and_id_and_props"),
]

WORKS = "works"
FAILS = "fails"
SKIPPED = "not measured"


def load():
    """Every check from every probe, normalised to one shape."""
    out = []
    for path, label in SOURCES:
        if not os.path.exists(path):
            continue
        with open(path) as fh:
            data = json.load(fh)
        # probe1: {"report": [{check, ok, error, note}]}
        for r in data.get("report", []):
            out.append({
                "probe": label,
                "name": r.get("check", ""),
                "verdict": WORKS if r.get("ok") else FAILS,
                "detail": (r.get("error") or r.get("detail") or "").strip(),
                "query": "",
                "note": (r.get("note") or "").strip(),
            })
        # probe2-6: {"checks": [{group, name, verdict, detail, query}]}
        for r in data.get("checks", []):
            v = str(r.get("verdict", "")).upper()
            out.append({
                "probe": label,
                "name": r.get("name", ""),
                "verdict": WORKS if v in ("OK", "YES")
                           else (SKIPPED if v == "SKIP" else FAILS),
                "detail": (r.get("detail") or "").strip(),
                "query": (r.get("query") or "").strip(),
                "note": "",
            })
    return out


def one_line(text, width=150):
    text = " ".join((text or "").split())
    return text[:width] + ("..." if len(text) > width else "")


def main() -> int:
    checks = load()
    if not checks:
        print("no probe reports found", file=sys.stderr)
        return 4

    by_probe = {}
    for c in checks:
        by_probe.setdefault(c["probe"], []).append(c)

    works = [c for c in checks if c["verdict"] == WORKS]
    fails = [c for c in checks if c["verdict"] == FAILS]
    skips = [c for c in checks if c["verdict"] == SKIPPED]

    # latest verdict per capability name wins; probes run in order
    order = {label: i for i, (_, label) in enumerate(SOURCES)}
    latest = {}
    for c in checks:
        if c["verdict"] == SKIPPED:
            continue
        prev = latest.get(c["name"])
        if prev is None or order[c["probe"]] >= order[prev["probe"]]:
            latest[c["name"]] = c

    print("# HydraDB 0.1.0 — what the query surface actually does")
    print()
    print("Generated by `tools/capabilities.py` from the probe reports in this")
    print("repository. Every verdict below came from a query sent to a live node,")
    print("not from documentation and not from memory. Regenerate it yourself:")
    print()
    print("    python3 tools/capabilities.py > HYDRADB-CAPABILITIES.md")
    print()
    print(f"**{len(checks)} checks across {len(by_probe)} probe runs: "
          f"{len(works)} worked, {len(fails)} did not, {len(skips)} were not "
          f"reached** (a probe skips the rest of a group once its precondition "
          f"fails).")
    print()

    print("## Read this part first: the probes disagree with each other")
    print()
    print("The first probe reported almost the entire surface as unsupported.")
    print("Probes 2-6 then found the working syntax and overturned eight of its")
    print("verdicts. The corrections are listed rather than quietly dropped,")
    print("because the lesson is the useful part:")
    print()
    print("> An \"unsupported\" verdict from a probe is a statement about the")
    print("> probe until the alternative shapes have been tried.")
    print()
    print("probe1 wrote `CREATE (n:Label {props})` with no integer id and")
    print("concluded labelled CREATE was unsupported. The engine wanted a")
    print("one-hop edge pattern with an integer id on both ends. The engine was")
    print("fine; the query was wrong.")
    print()
    print("| probe1 verdict | corrected by | working form |")
    print("| --- | --- | --- |")
    first = {c["name"]: c for c in by_probe.get("probe1", [])}
    later = {}
    for c in checks:
        if c["probe"] != "probe1" and c["verdict"] == WORKS:
            later.setdefault(c["name"], c)
    shown = 0
    for old, new in OVERTURNED:
        a, b = first.get(old), later.get(new)
        if not a or not b or a["verdict"] != FAILS:
            continue
        shown += 1
        form = one_line(b["query"] or b["detail"], 78).replace("|", "\\|")
        print(f"| `{old}` — not supported | {b['probe']} `{new}` | `{form}` |")
    print()
    print(f"**{shown} of probe1's verdicts are superseded. `probe-report.json`")
    print("is kept in the repository as the record of that first pass; it is NOT")
    print("the capability map. This file is.**")
    print()

    print("## Measured working")
    print()
    for c in sorted(works, key=lambda c: c["name"]):
        if latest.get(c["name"], c)["verdict"] != WORKS:
            continue
        q = one_line(c["query"], 110)
        print(f"- **{c['name']}** ({c['probe']})" + (f" — `{q}`" if q else ""))
    print()

    print("## Measured not working")
    print()
    print("Each line is the engine's own error, trimmed. Verdicts superseded by")
    print("the correction table above are excluded from this list.")
    print()
    superseded = {old for old, _ in OVERTURNED}
    for c in sorted(fails, key=lambda c: c["name"]):
        if latest.get(c["name"], c)["verdict"] != FAILS:
            continue
        if c["probe"] == "probe1" and c["name"] in superseded:
            continue
        print(f"- **{c['name']}** ({c['probe']}) — {one_line(c['detail'], 130)}")
    print()

    print("## Not reached")
    print()
    print("A probe stops a group once its precondition fails, so these were "
          "never sent. They are unknown, not unsupported — the distinction the "
          "correction table above exists to protect.")
    print()
    names = sorted({c["name"] for c in skips
                    if c["name"] not in latest})
    print(", ".join(f"`{n}`" for n in names) if names else "_none_")
    print()
    print("---")
    print()
    print("Produced while building `docket` for Hack Hydra. The probe suite is")
    print("`tools/probe*.py`; each report is committed beside it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
