#!/usr/bin/env python3
"""Build RESULTS.md from the judged output.

    python3 tools/report.py > RESULTS.md
    python3 tools/report.py --answers state/answers-500.jsonl \
                            --judged state/judged-500.jsonl \
                            --baseline state/judged-baseline.jsonl

Every number here is computed from the run files, not typed. That matters more
than it sounds: the accuracy figure, the per-category table and the calibration
pair have each been quoted by hand at least once during this build and at least
one of those quotes was wrong. A generated table cannot drift from the run.

The table it produces is the point of the whole eval. Accuracy alone says
almost nothing, because three different systems hide inside one average:

  RETRIEVAL STRONG   the evidence was found and the answer follows
  RETRIEVAL WEAK     nothing relevant was found, and refusing was CORRECT
  RETRIEVAL FINE,    the evidence was found and the answerer declined anyway
  ACCURACY LOW       -- the only one of the three that is a calibration bug

Joining per-category retrieval recall to per-category accuracy is what
separates them, so the report computes recall from the answers file rather than
asking the reader to hold two tables in their head.
"""
from __future__ import annotations

import argparse
import json
import os

STATE = os.environ.get("DOCKET_STATE", os.path.expanduser("~/docket/state"))


def load(path):
    """Append-only files: the last row for a question id wins."""
    rows = {}
    with open(path) as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except ValueError:
                continue
            qid = row.get("question_id")
            if qid:
                rows[qid] = row
    return rows


def pct(n, d):
    return None if not d else round(n / d, 4)


def recall_by_type(answers):
    """Did the evidence contain a gold session? Computed the same way
    score_retrieval does, so the two tools cannot disagree."""
    out = {}
    for row in answers.values():
        if row.get("is_abstention"):
            continue
        gold = set(row.get("gold_sessions") or [])
        if not gold:
            continue
        cited = set()
        for e in (row.get("evidence") or []):
            if e.get("session"):
                cited.add(e["session"])
        b = out.setdefault(row.get("question_type") or "unknown",
                           {"n": 0, "hit": 0})
        b["n"] += 1
        b["hit"] += 1 if (gold & cited) else 0
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--answers", default=os.path.join(STATE, "answers-500.jsonl"))
    ap.add_argument("--judged", default=os.path.join(STATE, "judged-500.jsonl"))
    ap.add_argument("--baseline",
                    default=os.path.join(STATE, "judged-baseline.jsonl"))
    a = ap.parse_args()

    for p in (a.answers, a.judged):
        if not os.path.exists(p):
            raise SystemExit("missing file: " + p)

    answers = load(a.answers)
    judged = load(a.judged)
    baseline = load(a.baseline) if os.path.exists(a.baseline) else {}

    real = [r for r in judged.values() if not r.get("is_abstention")]
    absts = [r for r in judged.values() if r.get("is_abstention")]

    correct = sum(1 for r in real if r.get("verdict") == "correct")
    wrong = sum(1 for r in real if r.get("verdict") == "incorrect")
    unjudged = sum(1 for r in real if r.get("verdict") == "unjudged")
    false_ref = sum(1 for r in real if r.get("kind") == "false_refusal")
    ret_miss = sum(1 for r in real if r.get("kind") == "retrieval_miss")
    graded = correct + wrong
    answered = graded - false_ref - ret_miss
    wrong_answers = wrong - false_ref - ret_miss

    refused_abs = sum(1 for r in absts if r.get("kind") == "refused")
    halluc = sum(1 for r in absts if r.get("kind") == "hallucinated")

    judges = {r.get("judge_model") for r in judged.values() if r.get("judge_model")}
    b_correct = sum(1 for r in baseline.values()
                    if not r.get("is_abstention") and r.get("verdict") == "correct")
    b_graded = sum(1 for r in baseline.values()
                   if not r.get("is_abstention")
                   and r.get("verdict") in ("correct", "incorrect"))

    print("# Results")
    print()
    print("Generated by `tools/report.py` from the run files. Regenerate:")
    print()
    print("    python3 tools/report.py > RESULTS.md")
    print()
    print(f"LongMemEval V1 oracle, all {len(judged)} questions "
          f"({len(real)} answerable, {len(absts)} abstention). "
          f"Judge: {', '.join(sorted(judges)) or 'none'}.")
    print()

    print("## Headline")
    print()
    print("| | |")
    print("| --- | --- |")
    print(f"| **Accuracy** | **{pct(correct, graded)}** ({correct}/{graded}) |")
    if b_graded:
        print(f"| No-memory baseline | {pct(b_correct, b_graded)} "
              f"({b_correct}/{b_graded}) |")
    print(f"| Precision when it answers | {pct(correct, answered)} "
          f"({correct}/{answered}) |")
    print(f"| Abstention refused correctly | {pct(refused_abs, len(absts))} "
          f"({refused_abs}/{len(absts)}) |")
    print(f"| Hallucinated on unanswerable | {halluc}/{len(absts)} |")
    print(f"| False refusal rate | {pct(false_ref, graded - ret_miss)} "
          f"({false_ref}/{graded - ret_miss}) |")
    print(f"| Unjudged | {unjudged} |")
    print()
    if b_graded is not None and b_graded:
        print(f"The baseline is the same questions and the same model with **no "
              f"evidence at all**. It is reported so the accuracy above cannot "
              f"be read as world knowledge leaking in.")
        print()
        print("> Caveat stated rather than buried: the baseline was instructed "
              "not to guess, so its score partly reflects that instruction. It "
              "shows a model that declines rather than guesses gets none of "
              "these questions; it does not show they are unguessable.")
        print()

    print("## Where the wrong answers go")
    print()
    print(f"Of {graded} graded answerable questions:")
    print()
    print(f"- **{correct} correct**")
    print(f"- **{wrong_answers} answered and wrong**")
    print(f"- **{false_ref} refused with a gold session in the evidence** "
          f"— a calibration failure, the answerer's fault")
    print(f"- **{ret_miss} refused with the gold session never retrieved** "
          f"— refusing was correct on what it was shown; the miss is retrieval's")
    print()
    print("Those last two are separated everywhere in this repo because they "
          "need opposite fixes. Merging them into one \"false refusal\" number "
          "points the diagnosis at the wrong layer, which happened here before "
          "the split existed.")
    print()

    print("## The three regimes")
    print()
    print("Retrieval recall is joined to accuracy per category. Read the rows, "
          "not the average.")
    print()
    rec = recall_by_type(answers)
    by_type = {}
    for r in real:
        t = r.get("question_type") or "unknown"
        b = by_type.setdefault(t, {"n": 0, "correct": 0, "incorrect": 0,
                                   "false_refusal": 0, "retrieval_miss": 0})
        b["n"] += 1
        if r.get("verdict") == "correct":
            b["correct"] += 1
        elif r.get("verdict") == "incorrect":
            b["incorrect"] += 1
        if r.get("kind") in ("false_refusal", "retrieval_miss"):
            b[r["kind"]] += 1

    print("| category | n | retrieval recall | accuracy | conversion | "
          "false refusals | retrieval misses |")
    print("| --- | --- | --- | --- | --- | --- | --- |")
    for name in sorted(by_type, key=lambda k: -(
            pct(by_type[k]["correct"], by_type[k]["correct"] + by_type[k]["incorrect"]) or 0)):
        b = by_type[name]
        g = b["correct"] + b["incorrect"]
        acc = pct(b["correct"], g)
        r = rec.get(name)
        rc = pct(r["hit"], r["n"]) if r else None
        conv = round(acc / rc, 3) if (acc and rc) else None
        print(f"| {name} | {b['n']} | {rc} | **{acc}** | {conv} | "
              f"{b['false_refusal']} | {b['retrieval_miss']} |")
    print()
    print("**conversion** = accuracy divided by retrieval recall: the share of "
          "questions whose evidence was found that also produced a right "
          "answer. A high recall with a low conversion is the answerer's "
          "problem, not the gate's.")
    print()

    if false_ref and answered:
        est = (correct + false_ref * (correct / answered)) / graded
        print("## Headroom")
        print()
        print(f"Converting the {false_ref} calibration failures at the "
              f"answerer's own precision of {pct(correct, answered)} would land "
              f"near **{round(est, 3)}**.")
        print()
        print("That is an estimate and not a result. It is here because it "
              "sizes the gap: over-refusal is worth roughly "
              f"{round((est - (correct / graded)) * 100)} accuracy points, "
              "which is why it is reported as the finding rather than as an "
              "excuse.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
